
struct inst_opcode_entry {
	uint8_t opcode[8];
	int numbytes;
	int argtype;
	const char *str;
};

struct inst_opcode_entry inst_opcodes[] = {
	{ .opcode = { 0x00 }, .str = "RLC B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x01 }, .str = "RLC C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x02 }, .str = "RLC D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x03 }, .str = "RLC E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x04 }, .str = "RLC H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x05 }, .str = "RLC L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x06 }, .str = "RLC (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x07 }, .str = "RLC A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x08 }, .str = "RRC B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x09 }, .str = "RRC C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x0A }, .str = "RRC D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x0B }, .str = "RRC E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x0C }, .str = "RRC H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x0D }, .str = "RRC L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x0E }, .str = "RRC (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x0F }, .str = "RRC A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x10 }, .str = "RL B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x11 }, .str = "RL C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x12 }, .str = "RL D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x13 }, .str = "RL E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x14 }, .str = "RL H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x15 }, .str = "RL L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x16 }, .str = "RL (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x17 }, .str = "RL A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x18 }, .str = "RR B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x19 }, .str = "RR C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x1A }, .str = "RR D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x1B }, .str = "RR E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x1C }, .str = "RR H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x1D }, .str = "RR L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x1E }, .str = "RR (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x1F }, .str = "RR A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x20 }, .str = "SLA B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x21 }, .str = "SLA C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x22 }, .str = "SLA D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x23 }, .str = "SLA E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x24 }, .str = "SLA H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x25 }, .str = "SLA L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x26 }, .str = "SLA (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x27 }, .str = "SLA A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x28 }, .str = "SRA B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x29 }, .str = "SRA C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x2A }, .str = "SRA D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x2B }, .str = "SRA E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x2C }, .str = "SRA H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x2D }, .str = "SRA L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x2E }, .str = "SRA (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x2F }, .str = "SRA A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x30 }, .str = "SLL B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x31 }, .str = "SLL C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x32 }, .str = "SLL D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x33 }, .str = "SLL E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x34 }, .str = "SLL H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x35 }, .str = "SLL L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x36 }, .str = "SLL (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x37 }, .str = "SLL A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x38 }, .str = "SRL B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x39 }, .str = "SRL C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x3A }, .str = "SRL D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x3B }, .str = "SRL E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x3C }, .str = "SRL H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x3D }, .str = "SRL L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x3E }, .str = "SRL (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x3F }, .str = "SRL A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x40 }, .str = "BIT 0, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x41 }, .str = "BIT 0, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x42 }, .str = "BIT 0, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x43 }, .str = "BIT 0, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x44 }, .str = "BIT 0, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x45 }, .str = "BIT 0, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x46 }, .str = "BIT 0, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x47 }, .str = "BIT 0, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x48 }, .str = "BIT 1, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x49 }, .str = "BIT 1, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x4A }, .str = "BIT 1, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x4B }, .str = "BIT 1, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x4C }, .str = "BIT 1, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x4D }, .str = "BIT 1, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x4E }, .str = "BIT 1, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x4F }, .str = "BIT 1, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x50 }, .str = "BIT 2, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x51 }, .str = "BIT 2, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x52 }, .str = "BIT 2, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x53 }, .str = "BIT 2, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x54 }, .str = "BIT 2, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x55 }, .str = "BIT 2, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x56 }, .str = "BIT 2, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x57 }, .str = "BIT 2, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x58 }, .str = "BIT 3, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x59 }, .str = "BIT 3, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x5A }, .str = "BIT 3, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x5B }, .str = "BIT 3, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x5C }, .str = "BIT 3, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x5D }, .str = "BIT 3, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x5E }, .str = "BIT 3, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x5F }, .str = "BIT 3, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x60 }, .str = "BIT 4, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x61 }, .str = "BIT 4, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x62 }, .str = "BIT 4, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x63 }, .str = "BIT 4, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x64 }, .str = "BIT 4, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x65 }, .str = "BIT 4, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x66 }, .str = "BIT 4, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x67 }, .str = "BIT 4, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x68 }, .str = "BIT 5, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x69 }, .str = "BIT 5, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x6A }, .str = "BIT 5, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x6B }, .str = "BIT 5, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x6C }, .str = "BIT 5, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x6D }, .str = "BIT 5, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x6E }, .str = "BIT 5, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x6F }, .str = "BIT 5, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x70 }, .str = "BIT 6, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x71 }, .str = "BIT 6, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x72 }, .str = "BIT 6, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x73 }, .str = "BIT 6, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x74 }, .str = "BIT 6, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x75 }, .str = "BIT 6, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x76 }, .str = "BIT 6, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x77 }, .str = "BIT 6, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x78 }, .str = "BIT 7, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x79 }, .str = "BIT 7, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x7A }, .str = "BIT 7, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x7B }, .str = "BIT 7, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x7C }, .str = "BIT 7, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x7D }, .str = "BIT 7, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x7E }, .str = "BIT 7, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x7F }, .str = "BIT 7, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x80 }, .str = "RES 0, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x81 }, .str = "RES 0, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x82 }, .str = "RES 0, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x83 }, .str = "RES 0, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x84 }, .str = "RES 0, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x85 }, .str = "RES 0, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x86 }, .str = "RES 0, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x87 }, .str = "RES 0, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x88 }, .str = "RES 1, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x89 }, .str = "RES 1, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x8A }, .str = "RES 1, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x8B }, .str = "RES 1, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x8C }, .str = "RES 1, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x8D }, .str = "RES 1, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x8E }, .str = "RES 1, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x8F }, .str = "RES 1, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x90 }, .str = "RES 2, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x91 }, .str = "RES 2, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x92 }, .str = "RES 2, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x93 }, .str = "RES 2, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x94 }, .str = "RES 2, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x95 }, .str = "RES 2, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x96 }, .str = "RES 2, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x97 }, .str = "RES 2, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x98 }, .str = "RES 3, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x99 }, .str = "RES 3, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x9A }, .str = "RES 3, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x9B }, .str = "RES 3, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x9C }, .str = "RES 3, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x9D }, .str = "RES 3, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x9E }, .str = "RES 3, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0x9F }, .str = "RES 3, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xA0 }, .str = "RES 4, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xA1 }, .str = "RES 4, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xA2 }, .str = "RES 4, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xA3 }, .str = "RES 4, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xA4 }, .str = "RES 4, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xA5 }, .str = "RES 4, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xA6 }, .str = "RES 4, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xA7 }, .str = "RES 4, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xA8 }, .str = "RES 5, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xA9 }, .str = "RES 5, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xAA }, .str = "RES 5, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xAB }, .str = "RES 5, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xAC }, .str = "RES 5, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xAD }, .str = "RES 5, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xAE }, .str = "RES 5, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xAF }, .str = "RES 5, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xB0 }, .str = "RES 6, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xB1 }, .str = "RES 6, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xB2 }, .str = "RES 6, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xB3 }, .str = "RES 6, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xB4 }, .str = "RES 6, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xB5 }, .str = "RES 6, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xB6 }, .str = "RES 6, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xB7 }, .str = "RES 6, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xB8 }, .str = "RES 7, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xB9 }, .str = "RES 7, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xBA }, .str = "RES 7, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xBB }, .str = "RES 7, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xBC }, .str = "RES 7, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xBD }, .str = "RES 7, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xBE }, .str = "RES 7, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xBF }, .str = "RES 7, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xC0 }, .str = "SET 0, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xC1 }, .str = "SET 0, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xC2 }, .str = "SET 0, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xC3 }, .str = "SET 0, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xC4 }, .str = "SET 0, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xC5 }, .str = "SET 0, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xC6 }, .str = "SET 0, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xC7 }, .str = "SET 0, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xC8 }, .str = "SET 1, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xC9 }, .str = "SET 1, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCA }, .str = "SET 1, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB }, .str = "SET 1, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCC }, .str = "SET 1, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCD }, .str = "SET 1, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCE }, .str = "SET 1, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCF }, .str = "SET 1, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xD0 }, .str = "SET 2, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xD1 }, .str = "SET 2, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xD2 }, .str = "SET 2, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xD3 }, .str = "SET 2, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xD4 }, .str = "SET 2, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xD5 }, .str = "SET 2, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xD6 }, .str = "SET 2, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xD7 }, .str = "SET 2, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xD8 }, .str = "SET 3, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xD9 }, .str = "SET 3, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xDA }, .str = "SET 3, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xDB }, .str = "SET 3, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xDC }, .str = "SET 3, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xDD }, .str = "SET 3, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xDE }, .str = "SET 3, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xDF }, .str = "SET 3, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xE0 }, .str = "SET 4, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xE1 }, .str = "SET 4, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xE2 }, .str = "SET 4, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xE3 }, .str = "SET 4, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xE4 }, .str = "SET 4, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xE5 }, .str = "SET 4, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xE6 }, .str = "SET 4, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xE7 }, .str = "SET 4, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xE8 }, .str = "SET 5, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xE9 }, .str = "SET 5, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xEA }, .str = "SET 5, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xEB }, .str = "SET 5, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xEC }, .str = "SET 5, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED }, .str = "SET 5, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xEE }, .str = "SET 5, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xEF }, .str = "SET 5, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xF0 }, .str = "SET 6, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xF1 }, .str = "SET 6, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xF2 }, .str = "SET 6, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xF3 }, .str = "SET 6, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xF4 }, .str = "SET 6, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xF5 }, .str = "SET 6, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xF6 }, .str = "SET 6, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xF7 }, .str = "SET 6, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xF8 }, .str = "SET 7, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xF9 }, .str = "SET 7, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xFA }, .str = "SET 7, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xFB }, .str = "SET 7, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xFC }, .str = "SET 7, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xFD }, .str = "SET 7, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xFE }, .str = "SET 7, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xFF }, .str = "SET 7, A", .numbytes = 1, .argtype = 0, },
};
