
struct inst_opcode_entry {
	uint8_t opcode[8];
	int opcode_len;
	int numbytes;
	int argtype;
	const char *str;
};

struct inst_opcode_entry inst_opcodes[] = {
	{ .opcode = {  0x00 }, .opcode_len = 1, .str = "NOP", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x01 }, .opcode_len = 1, .str = "LD BC, ^", .numbytes = 3, .argtype = 0, },
	{ .opcode = {  0x02 }, .opcode_len = 1, .str = "LD BC, (A)", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x03 }, .opcode_len = 1, .str = "INC BC", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x04 }, .opcode_len = 1, .str = "INC B", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x05 }, .opcode_len = 1, .str = "DEC B", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x06 }, .opcode_len = 1, .str = "LD B, $", .numbytes = 2, .argtype = 0, },
	{ .opcode = {  0x07 }, .opcode_len = 1, .str = "RLCA", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x08 }, .opcode_len = 1, .str = "EX AF, AF'", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x09 }, .opcode_len = 1, .str = "ADD HL, BC", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x0A }, .opcode_len = 1, .str = "LD A, (BC)", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x0B }, .opcode_len = 1, .str = "DEC BC", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x0C }, .opcode_len = 1, .str = "INC C", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x0D }, .opcode_len = 1, .str = "DEC C", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x0E }, .opcode_len = 1, .str = "LD C, $", .numbytes = 2, .argtype = 0, },
	{ .opcode = {  0x0F }, .opcode_len = 1, .str = "RRCA", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x10 }, .opcode_len = 1, .str = "DJNZ %", .numbytes = 2, .argtype = 0, },
	{ .opcode = {  0x11 }, .opcode_len = 1, .str = "LD DE, ^", .numbytes = 3, .argtype = 0, },
	{ .opcode = {  0x12 }, .opcode_len = 1, .str = "LD (DE), A", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x13 }, .opcode_len = 1, .str = "INC DE", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x14 }, .opcode_len = 1, .str = "INC D", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x15 }, .opcode_len = 1, .str = "DEC D", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x16 }, .opcode_len = 1, .str = "LD D, $", .numbytes = 2, .argtype = 0, },
	{ .opcode = {  0x17 }, .opcode_len = 1, .str = "RLA", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x18 }, .opcode_len = 1, .str = "JR %", .numbytes = 2, .argtype = 0, },
	{ .opcode = {  0x19 }, .opcode_len = 1, .str = "ADD HL, DE", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x1A }, .opcode_len = 1, .str = "LD A, (DE)", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x1B }, .opcode_len = 1, .str = "DEC DE", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x1C }, .opcode_len = 1, .str = "INC E", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x1D }, .opcode_len = 1, .str = "DEC E", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x1E }, .opcode_len = 1, .str = "LD E, $", .numbytes = 2, .argtype = 0, },
	{ .opcode = {  0x1F }, .opcode_len = 1, .str = "RRA", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x20 }, .opcode_len = 1, .str = "JR NZ, %", .numbytes = 2, .argtype = 0, },
	{ .opcode = {  0x21 }, .opcode_len = 1, .str = "LD HL, ^", .numbytes = 3, .argtype = 0, },
	{ .opcode = {  0x22 }, .opcode_len = 1, .str = "LD (^), HL", .numbytes = 3, .argtype = 0, },
	{ .opcode = {  0x23 }, .opcode_len = 1, .str = "INC HL", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x24 }, .opcode_len = 1, .str = "INC H", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x25 }, .opcode_len = 1, .str = "DEC H", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x26 }, .opcode_len = 1, .str = "LD H, $", .numbytes = 2, .argtype = 0, },
	{ .opcode = {  0x27 }, .opcode_len = 1, .str = "DAA", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x28 }, .opcode_len = 1, .str = "JR Z, %", .numbytes = 2, .argtype = 0, },
	{ .opcode = {  0x29 }, .opcode_len = 1, .str = "ADD HL, HL", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x2A }, .opcode_len = 1, .str = "LD HL, (^)", .numbytes = 3, .argtype = 0, },
	{ .opcode = {  0x2B }, .opcode_len = 1, .str = "DEC HL", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x2C }, .opcode_len = 1, .str = "INC L", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x2D }, .opcode_len = 1, .str = "DEC L", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x2E }, .opcode_len = 1, .str = "LD L, $", .numbytes = 2, .argtype = 0, },
	{ .opcode = {  0x2F }, .opcode_len = 1, .str = "CPL", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x30 }, .opcode_len = 1, .str = "JR NC, %", .numbytes = 2, .argtype = 0, },
	{ .opcode = {  0x31 }, .opcode_len = 1, .str = "LD SP, ^", .numbytes = 3, .argtype = 0, },
	{ .opcode = {  0x32 }, .opcode_len = 1, .str = "LD (^), A", .numbytes = 3, .argtype = 0, },
	{ .opcode = {  0x33 }, .opcode_len = 1, .str = "INC SP", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x34 }, .opcode_len = 1, .str = "INC (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x35 }, .opcode_len = 1, .str = "DEC (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x36 }, .opcode_len = 1, .str = "LD (HL), $", .numbytes = 2, .argtype = 0, },
	{ .opcode = {  0x37 }, .opcode_len = 1, .str = "SCF", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x38 }, .opcode_len = 1, .str = "JR C, %", .numbytes = 2, .argtype = 0, },
	{ .opcode = {  0x39 }, .opcode_len = 1, .str = "ADD HL, SP", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x3A }, .opcode_len = 1, .str = "LD A, (^)", .numbytes = 3, .argtype = 0, },
	{ .opcode = {  0x3B }, .opcode_len = 1, .str = "DEC SP", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x3C }, .opcode_len = 1, .str = "INC A", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x3D }, .opcode_len = 1, .str = "DEC A", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x3E }, .opcode_len = 1, .str = "LD A, $", .numbytes = 2, .argtype = 0, },
	{ .opcode = {  0x3F }, .opcode_len = 1, .str = "CCF", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x40 }, .opcode_len = 1, .str = "LD B, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x41 }, .opcode_len = 1, .str = "LD B, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x42 }, .opcode_len = 1, .str = "LD B, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x43 }, .opcode_len = 1, .str = "LD B, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x44 }, .opcode_len = 1, .str = "LD B, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x45 }, .opcode_len = 1, .str = "LD B, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x46 }, .opcode_len = 1, .str = "LD B, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x47 }, .opcode_len = 1, .str = "LD B, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x48 }, .opcode_len = 1, .str = "LD C, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x49 }, .opcode_len = 1, .str = "LD C, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x4A }, .opcode_len = 1, .str = "LD C, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x4B }, .opcode_len = 1, .str = "LD C, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x4C }, .opcode_len = 1, .str = "LD C, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x4D }, .opcode_len = 1, .str = "LD C, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x4E }, .opcode_len = 1, .str = "LD C, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x4F }, .opcode_len = 1, .str = "LD C, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x50 }, .opcode_len = 1, .str = "LD D, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x51 }, .opcode_len = 1, .str = "LD D, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x52 }, .opcode_len = 1, .str = "LD D, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x53 }, .opcode_len = 1, .str = "LD D, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x54 }, .opcode_len = 1, .str = "LD D, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x55 }, .opcode_len = 1, .str = "LD D, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x56 }, .opcode_len = 1, .str = "LD D, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x57 }, .opcode_len = 1, .str = "LD D, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x58 }, .opcode_len = 1, .str = "LD E, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x59 }, .opcode_len = 1, .str = "LD E, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x5A }, .opcode_len = 1, .str = "LD E, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x5B }, .opcode_len = 1, .str = "LD E, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x5C }, .opcode_len = 1, .str = "LD E, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x5D }, .opcode_len = 1, .str = "LD E, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x5E }, .opcode_len = 1, .str = "LD E, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x5F }, .opcode_len = 1, .str = "LD E, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x60 }, .opcode_len = 1, .str = "LD H, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x61 }, .opcode_len = 1, .str = "LD H, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x62 }, .opcode_len = 1, .str = "LD H, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x63 }, .opcode_len = 1, .str = "LD H, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x64 }, .opcode_len = 1, .str = "LD H, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x65 }, .opcode_len = 1, .str = "LD H, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x66 }, .opcode_len = 1, .str = "LD H, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x67 }, .opcode_len = 1, .str = "LD H, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x68 }, .opcode_len = 1, .str = "LD L, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x69 }, .opcode_len = 1, .str = "LD L, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x6A }, .opcode_len = 1, .str = "LD L, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x6B }, .opcode_len = 1, .str = "LD L, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x6C }, .opcode_len = 1, .str = "LD L, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x6D }, .opcode_len = 1, .str = "LD L, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x6E }, .opcode_len = 1, .str = "LD L, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x6F }, .opcode_len = 1, .str = "LD L, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x70 }, .opcode_len = 1, .str = "LD (HL), B", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x71 }, .opcode_len = 1, .str = "LD (HL), C", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x72 }, .opcode_len = 1, .str = "LD (HL), D", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x73 }, .opcode_len = 1, .str = "LD (HL), E", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x74 }, .opcode_len = 1, .str = "LD (HL), H", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x75 }, .opcode_len = 1, .str = "LD (HL), L", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x76 }, .opcode_len = 1, .str = "HALT", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x77 }, .opcode_len = 1, .str = "LD (HL), A", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x78 }, .opcode_len = 1, .str = "LD A, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x79 }, .opcode_len = 1, .str = "LD A, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x7A }, .opcode_len = 1, .str = "LD A, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x7B }, .opcode_len = 1, .str = "LD A, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x7C }, .opcode_len = 1, .str = "LD A, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x7D }, .opcode_len = 1, .str = "LD A, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x7E }, .opcode_len = 1, .str = "LD A, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x7F }, .opcode_len = 1, .str = "LD A, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x80 }, .opcode_len = 1, .str = "ADD A, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x81 }, .opcode_len = 1, .str = "ADD A, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x82 }, .opcode_len = 1, .str = "ADD A, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x83 }, .opcode_len = 1, .str = "ADD A, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x84 }, .opcode_len = 1, .str = "ADD A, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x85 }, .opcode_len = 1, .str = "ADD A, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x86 }, .opcode_len = 1, .str = "ADD A, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x87 }, .opcode_len = 1, .str = "ADD A, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x88 }, .opcode_len = 1, .str = "ADC A, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x89 }, .opcode_len = 1, .str = "ADC A, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x8A }, .opcode_len = 1, .str = "ADC A, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x8B }, .opcode_len = 1, .str = "ADC A, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x8C }, .opcode_len = 1, .str = "ADC A, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x8D }, .opcode_len = 1, .str = "ADC A, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x8E }, .opcode_len = 1, .str = "ADC A, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x8F }, .opcode_len = 1, .str = "ADC A, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x90 }, .opcode_len = 1, .str = "SUB A, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x91 }, .opcode_len = 1, .str = "SUB A, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x92 }, .opcode_len = 1, .str = "SUB A, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x93 }, .opcode_len = 1, .str = "SUB A, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x94 }, .opcode_len = 1, .str = "SUB A, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x95 }, .opcode_len = 1, .str = "SUB A, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x96 }, .opcode_len = 1, .str = "SUB A, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x97 }, .opcode_len = 1, .str = "SUB A, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x98 }, .opcode_len = 1, .str = "SBC A, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x99 }, .opcode_len = 1, .str = "SBC A, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x9A }, .opcode_len = 1, .str = "SBC A, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x9B }, .opcode_len = 1, .str = "SBC A, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x9C }, .opcode_len = 1, .str = "SBC A, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x9D }, .opcode_len = 1, .str = "SBC A, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x9E }, .opcode_len = 1, .str = "SBC A, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0x9F }, .opcode_len = 1, .str = "SBC A, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xA0 }, .opcode_len = 1, .str = "AND A, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xA1 }, .opcode_len = 1, .str = "AND A, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xA2 }, .opcode_len = 1, .str = "AND A, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xA3 }, .opcode_len = 1, .str = "AND A, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xA4 }, .opcode_len = 1, .str = "AND A, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xA5 }, .opcode_len = 1, .str = "AND A, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xA6 }, .opcode_len = 1, .str = "AND A, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xA7 }, .opcode_len = 1, .str = "AND A, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xA8 }, .opcode_len = 1, .str = "XOR A, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xA9 }, .opcode_len = 1, .str = "XOR A, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xAA }, .opcode_len = 1, .str = "XOR A, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xAB }, .opcode_len = 1, .str = "XOR A, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xAC }, .opcode_len = 1, .str = "XOR A, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xAD }, .opcode_len = 1, .str = "XOR A, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xAE }, .opcode_len = 1, .str = "XOR A, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xAF }, .opcode_len = 1, .str = "XOR A, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xB0 }, .opcode_len = 1, .str = "OR A, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xB1 }, .opcode_len = 1, .str = "OR A, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xB2 }, .opcode_len = 1, .str = "OR A, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xB3 }, .opcode_len = 1, .str = "OR A, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xB4 }, .opcode_len = 1, .str = "OR A, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xB5 }, .opcode_len = 1, .str = "OR A, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xB6 }, .opcode_len = 1, .str = "OR A, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xB7 }, .opcode_len = 1, .str = "OR A, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xB8 }, .opcode_len = 1, .str = "CP B", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xB9 }, .opcode_len = 1, .str = "CP C", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xBA }, .opcode_len = 1, .str = "CP D", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xBB }, .opcode_len = 1, .str = "CP E", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xBC }, .opcode_len = 1, .str = "CP H", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xBD }, .opcode_len = 1, .str = "CP L", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xBE }, .opcode_len = 1, .str = "CP (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xBF }, .opcode_len = 1, .str = "CP A", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xC0 }, .opcode_len = 1, .str = "RET NZ", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xC1 }, .opcode_len = 1, .str = "POP BC", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xC2 }, .opcode_len = 1, .str = "JP NZ, ^", .numbytes = 3, .argtype = 0, },
	{ .opcode = {  0xC3 }, .opcode_len = 1, .str = "JP ^", .numbytes = 3, .argtype = 0, },
	{ .opcode = {  0xC4 }, .opcode_len = 1, .str = "CALL NZ, ^", .numbytes = 3, .argtype = 0, },
	{ .opcode = {  0xC5 }, .opcode_len = 1, .str = "PUSH BC", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xC6 }, .opcode_len = 1, .str = "ADD A, $", .numbytes = 2, .argtype = 0, },
	{ .opcode = {  0xC7 }, .opcode_len = 1, .str = "RST 00", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xC8 }, .opcode_len = 1, .str = "RET Z", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xC9 }, .opcode_len = 1, .str = "RET", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xCA }, .opcode_len = 1, .str = "JP Z, ^", .numbytes = 3, .argtype = 0, },
//	CB
	{ .opcode = {  0xCC }, .opcode_len = 1, .str = "CALL Z, ^", .numbytes = 3, .argtype = 0, },
	{ .opcode = {  0xCD }, .opcode_len = 1, .str = "CALL ^", .numbytes = 3, .argtype = 0, },
	{ .opcode = {  0xCE }, .opcode_len = 1, .str = "ADC A, $", .numbytes = 2, .argtype = 0, },
	{ .opcode = {  0xCF }, .opcode_len = 1, .str = "RST 08", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xD0 }, .opcode_len = 1, .str = "RET NC", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xD1 }, .opcode_len = 1, .str = "POP DE", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xD2 }, .opcode_len = 1, .str = "JP NC, ^", .numbytes = 3, .argtype = 0, },
	{ .opcode = {  0xD3 }, .opcode_len = 1, .str = "OUT ($), A", .numbytes = 2, .argtype = 0, },
	{ .opcode = {  0xD4 }, .opcode_len = 1, .str = "CALL NC, ^", .numbytes = 3, .argtype = 0, },
	{ .opcode = {  0xD5 }, .opcode_len = 1, .str = "PUSH DE", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xD6 }, .opcode_len = 1, .str = "SUB $", .numbytes = 2, .argtype = 0, },
	{ .opcode = {  0xD7 }, .opcode_len = 1, .str = "RST 10", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xD8 }, .opcode_len = 1, .str = "RET C", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xD9 }, .opcode_len = 1, .str = "EXX", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xDA }, .opcode_len = 1, .str = "JP C, ^", .numbytes = 3, .argtype = 0, },
	{ .opcode = {  0xDB }, .opcode_len = 1, .str = "IN A, ($)", .numbytes = 2, .argtype = 0, },
	{ .opcode = {  0xDC }, .opcode_len = 1, .str = "CALL C, ^", .numbytes = 3, .argtype = 0, },
// DD
	{ .opcode = {  0xDE }, .opcode_len = 1, .str = "SBC A, $", .numbytes = 2, .argtype = 0, },
	{ .opcode = {  0xDF }, .opcode_len = 1, .str = "RST 18", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xE0 }, .opcode_len = 1, .str = "RET PO", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xE1 }, .opcode_len = 1, .str = "POP HL", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xE2 }, .opcode_len = 1, .str = "JP PO, ^", .numbytes = 3, .argtype = 0, },
	{ .opcode = {  0xE3 }, .opcode_len = 1, .str = "EX (SP), HL", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xE4 }, .opcode_len = 1, .str = "CALL PO, ^", .numbytes = 3, .argtype = 0, },
	{ .opcode = {  0xE5 }, .opcode_len = 1, .str = "PUSH HL", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xE6 }, .opcode_len = 1, .str = "AND $", .numbytes = 2, .argtype = 0, },
	{ .opcode = {  0xE7 }, .opcode_len = 1, .str = "RST 20", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xE8 }, .opcode_len = 1, .str = "RET PE", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xE9 }, .opcode_len = 1, .str = "JP HL", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xEA }, .opcode_len = 1, .str = "JP PE, ^", .numbytes = 3, .argtype = 0, },
	{ .opcode = {  0xEB }, .opcode_len = 1, .str = "EX DE, HL", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xEC }, .opcode_len = 1, .str = "CALL PE, ^", .numbytes = 3, .argtype = 0, },
// ED
	{ .opcode = {  0xEE }, .opcode_len = 1, .str = "XOR $", .numbytes = 2, .argtype = 0, },
	{ .opcode = {  0xEF }, .opcode_len = 1, .str = "RST 28", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xF0 }, .opcode_len = 1, .str = "RET P", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xF1 }, .opcode_len = 1, .str = "POP AF", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xF2 }, .opcode_len = 1, .str = "JP P, ^", .numbytes = 3, .argtype = 0, },
	{ .opcode = {  0xF3 }, .opcode_len = 1, .str = "DI", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xF4 }, .opcode_len = 1, .str = "CALL P, ^", .numbytes = 3, .argtype = 0, },
	{ .opcode = {  0xF5 }, .opcode_len = 1, .str = "PUSH AF", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xF6 }, .opcode_len = 1, .str = "OR $", .numbytes = 2, .argtype = 0, },
	{ .opcode = {  0xF7 }, .opcode_len = 1, .str = "RST 30", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xF8 }, .opcode_len = 1, .str = "RET M", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xF9 }, .opcode_len = 1, .str = "LD SP, HL", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xFA }, .opcode_len = 1, .str = "JP M, ^", .numbytes = 3, .argtype = 0, },
	{ .opcode = {  0xFB }, .opcode_len = 1, .str = "EI", .numbytes = 1, .argtype = 0, },
	{ .opcode = {  0xFC }, .opcode_len = 1, .str = "CALL M, ^", .numbytes = 3, .argtype = 0, },
// FD
	{ .opcode = {  0xFE }, .opcode_len = 1, .str = "CP $", .numbytes = 2, .argtype = 0, },
	{ .opcode = {  0xFF }, .opcode_len = 1, .str = "RST 38", .numbytes = 1, .argtype = 0, },

	{ .opcode = { 0xCB, 0x00 }, .opcode_len = 2, .str = "RLC B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x01 }, .opcode_len = 2, .str = "RLC C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x02 }, .opcode_len = 2, .str = "RLC D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x03 }, .opcode_len = 2, .str = "RLC E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x04 }, .opcode_len = 2, .str = "RLC H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x05 }, .opcode_len = 2, .str = "RLC L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x06 }, .opcode_len = 2, .str = "RLC (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x07 }, .opcode_len = 2, .str = "RLC A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x08 }, .opcode_len = 2, .str = "RRC B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x09 }, .opcode_len = 2, .str = "RRC C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x0A }, .opcode_len = 2, .str = "RRC D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x0B }, .opcode_len = 2, .str = "RRC E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x0C }, .opcode_len = 2, .str = "RRC H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x0D }, .opcode_len = 2, .str = "RRC L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x0E }, .opcode_len = 2, .str = "RRC (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x0F }, .opcode_len = 2, .str = "RRC A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x10 }, .opcode_len = 2, .str = "RL B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x11 }, .opcode_len = 2, .str = "RL C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x12 }, .opcode_len = 2, .str = "RL D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x13 }, .opcode_len = 2, .str = "RL E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x14 }, .opcode_len = 2, .str = "RL H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x15 }, .opcode_len = 2, .str = "RL L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x16 }, .opcode_len = 2, .str = "RL (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x17 }, .opcode_len = 2, .str = "RL A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x18 }, .opcode_len = 2, .str = "RR B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x19 }, .opcode_len = 2, .str = "RR C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x1A }, .opcode_len = 2, .str = "RR D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x1B }, .opcode_len = 2, .str = "RR E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x1C }, .opcode_len = 2, .str = "RR H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x1D }, .opcode_len = 2, .str = "RR L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x1E }, .opcode_len = 2, .str = "RR (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x1F }, .opcode_len = 2, .str = "RR A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x20 }, .opcode_len = 2, .str = "SLA B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x21 }, .opcode_len = 2, .str = "SLA C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x22 }, .opcode_len = 2, .str = "SLA D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x23 }, .opcode_len = 2, .str = "SLA E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x24 }, .opcode_len = 2, .str = "SLA H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x25 }, .opcode_len = 2, .str = "SLA L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x26 }, .opcode_len = 2, .str = "SLA (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x27 }, .opcode_len = 2, .str = "SLA A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x28 }, .opcode_len = 2, .str = "SRA B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x29 }, .opcode_len = 2, .str = "SRA C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x2A }, .opcode_len = 2, .str = "SRA D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x2B }, .opcode_len = 2, .str = "SRA E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x2C }, .opcode_len = 2, .str = "SRA H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x2D }, .opcode_len = 2, .str = "SRA L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x2E }, .opcode_len = 2, .str = "SRA (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x2F }, .opcode_len = 2, .str = "SRA A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x30 }, .opcode_len = 2, .str = "SLL B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x31 }, .opcode_len = 2, .str = "SLL C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x32 }, .opcode_len = 2, .str = "SLL D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x33 }, .opcode_len = 2, .str = "SLL E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x34 }, .opcode_len = 2, .str = "SLL H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x35 }, .opcode_len = 2, .str = "SLL L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x36 }, .opcode_len = 2, .str = "SLL (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x37 }, .opcode_len = 2, .str = "SLL A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x38 }, .opcode_len = 2, .str = "SRL B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x39 }, .opcode_len = 2, .str = "SRL C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x3A }, .opcode_len = 2, .str = "SRL D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x3B }, .opcode_len = 2, .str = "SRL E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x3C }, .opcode_len = 2, .str = "SRL H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x3D }, .opcode_len = 2, .str = "SRL L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x3E }, .opcode_len = 2, .str = "SRL (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x3F }, .opcode_len = 2, .str = "SRL A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x40 }, .opcode_len = 2, .str = "BIT 0, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x41 }, .opcode_len = 2, .str = "BIT 0, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x42 }, .opcode_len = 2, .str = "BIT 0, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x43 }, .opcode_len = 2, .str = "BIT 0, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x44 }, .opcode_len = 2, .str = "BIT 0, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x45 }, .opcode_len = 2, .str = "BIT 0, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x46 }, .opcode_len = 2, .str = "BIT 0, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x47 }, .opcode_len = 2, .str = "BIT 0, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x48 }, .opcode_len = 2, .str = "BIT 1, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x49 }, .opcode_len = 2, .str = "BIT 1, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x4A }, .opcode_len = 2, .str = "BIT 1, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x4B }, .opcode_len = 2, .str = "BIT 1, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x4C }, .opcode_len = 2, .str = "BIT 1, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x4D }, .opcode_len = 2, .str = "BIT 1, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x4E }, .opcode_len = 2, .str = "BIT 1, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x4F }, .opcode_len = 2, .str = "BIT 1, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x50 }, .opcode_len = 2, .str = "BIT 2, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x51 }, .opcode_len = 2, .str = "BIT 2, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x52 }, .opcode_len = 2, .str = "BIT 2, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x53 }, .opcode_len = 2, .str = "BIT 2, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x54 }, .opcode_len = 2, .str = "BIT 2, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x55 }, .opcode_len = 2, .str = "BIT 2, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x56 }, .opcode_len = 2, .str = "BIT 2, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x57 }, .opcode_len = 2, .str = "BIT 2, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x58 }, .opcode_len = 2, .str = "BIT 3, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x59 }, .opcode_len = 2, .str = "BIT 3, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x5A }, .opcode_len = 2, .str = "BIT 3, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x5B }, .opcode_len = 2, .str = "BIT 3, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x5C }, .opcode_len = 2, .str = "BIT 3, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x5D }, .opcode_len = 2, .str = "BIT 3, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x5E }, .opcode_len = 2, .str = "BIT 3, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x5F }, .opcode_len = 2, .str = "BIT 3, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x60 }, .opcode_len = 2, .str = "BIT 4, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x61 }, .opcode_len = 2, .str = "BIT 4, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x62 }, .opcode_len = 2, .str = "BIT 4, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x63 }, .opcode_len = 2, .str = "BIT 4, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x64 }, .opcode_len = 2, .str = "BIT 4, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x65 }, .opcode_len = 2, .str = "BIT 4, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x66 }, .opcode_len = 2, .str = "BIT 4, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x67 }, .opcode_len = 2, .str = "BIT 4, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x68 }, .opcode_len = 2, .str = "BIT 5, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x69 }, .opcode_len = 2, .str = "BIT 5, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x6A }, .opcode_len = 2, .str = "BIT 5, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x6B }, .opcode_len = 2, .str = "BIT 5, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x6C }, .opcode_len = 2, .str = "BIT 5, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x6D }, .opcode_len = 2, .str = "BIT 5, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x6E }, .opcode_len = 2, .str = "BIT 5, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x6F }, .opcode_len = 2, .str = "BIT 5, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x70 }, .opcode_len = 2, .str = "BIT 6, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x71 }, .opcode_len = 2, .str = "BIT 6, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x72 }, .opcode_len = 2, .str = "BIT 6, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x73 }, .opcode_len = 2, .str = "BIT 6, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x74 }, .opcode_len = 2, .str = "BIT 6, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x75 }, .opcode_len = 2, .str = "BIT 6, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x76 }, .opcode_len = 2, .str = "BIT 6, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x77 }, .opcode_len = 2, .str = "BIT 6, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x78 }, .opcode_len = 2, .str = "BIT 7, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x79 }, .opcode_len = 2, .str = "BIT 7, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x7A }, .opcode_len = 2, .str = "BIT 7, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x7B }, .opcode_len = 2, .str = "BIT 7, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x7C }, .opcode_len = 2, .str = "BIT 7, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x7D }, .opcode_len = 2, .str = "BIT 7, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x7E }, .opcode_len = 2, .str = "BIT 7, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x7F }, .opcode_len = 2, .str = "BIT 7, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x80 }, .opcode_len = 2, .str = "RES 0, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x81 }, .opcode_len = 2, .str = "RES 0, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x82 }, .opcode_len = 2, .str = "RES 0, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x83 }, .opcode_len = 2, .str = "RES 0, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x84 }, .opcode_len = 2, .str = "RES 0, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x85 }, .opcode_len = 2, .str = "RES 0, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x86 }, .opcode_len = 2, .str = "RES 0, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x87 }, .opcode_len = 2, .str = "RES 0, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x88 }, .opcode_len = 2, .str = "RES 1, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x89 }, .opcode_len = 2, .str = "RES 1, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x8A }, .opcode_len = 2, .str = "RES 1, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x8B }, .opcode_len = 2, .str = "RES 1, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x8C }, .opcode_len = 2, .str = "RES 1, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x8D }, .opcode_len = 2, .str = "RES 1, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x8E }, .opcode_len = 2, .str = "RES 1, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x8F }, .opcode_len = 2, .str = "RES 1, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x90 }, .opcode_len = 2, .str = "RES 2, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x91 }, .opcode_len = 2, .str = "RES 2, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x92 }, .opcode_len = 2, .str = "RES 2, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x93 }, .opcode_len = 2, .str = "RES 2, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x94 }, .opcode_len = 2, .str = "RES 2, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x95 }, .opcode_len = 2, .str = "RES 2, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x96 }, .opcode_len = 2, .str = "RES 2, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x97 }, .opcode_len = 2, .str = "RES 2, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x98 }, .opcode_len = 2, .str = "RES 3, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x99 }, .opcode_len = 2, .str = "RES 3, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x9A }, .opcode_len = 2, .str = "RES 3, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x9B }, .opcode_len = 2, .str = "RES 3, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x9C }, .opcode_len = 2, .str = "RES 3, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x9D }, .opcode_len = 2, .str = "RES 3, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x9E }, .opcode_len = 2, .str = "RES 3, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0x9F }, .opcode_len = 2, .str = "RES 3, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xA0 }, .opcode_len = 2, .str = "RES 4, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xA1 }, .opcode_len = 2, .str = "RES 4, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xA2 }, .opcode_len = 2, .str = "RES 4, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xA3 }, .opcode_len = 2, .str = "RES 4, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xA4 }, .opcode_len = 2, .str = "RES 4, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xA5 }, .opcode_len = 2, .str = "RES 4, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xA6 }, .opcode_len = 2, .str = "RES 4, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xA7 }, .opcode_len = 2, .str = "RES 4, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xA8 }, .opcode_len = 2, .str = "RES 5, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xA9 }, .opcode_len = 2, .str = "RES 5, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xAA }, .opcode_len = 2, .str = "RES 5, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xAB }, .opcode_len = 2, .str = "RES 5, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xAC }, .opcode_len = 2, .str = "RES 5, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xAD }, .opcode_len = 2, .str = "RES 5, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xAE }, .opcode_len = 2, .str = "RES 5, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xAF }, .opcode_len = 2, .str = "RES 5, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xB0 }, .opcode_len = 2, .str = "RES 6, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xB1 }, .opcode_len = 2, .str = "RES 6, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xB2 }, .opcode_len = 2, .str = "RES 6, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xB3 }, .opcode_len = 2, .str = "RES 6, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xB4 }, .opcode_len = 2, .str = "RES 6, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xB5 }, .opcode_len = 2, .str = "RES 6, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xB6 }, .opcode_len = 2, .str = "RES 6, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xB7 }, .opcode_len = 2, .str = "RES 6, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xB8 }, .opcode_len = 2, .str = "RES 7, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xB9 }, .opcode_len = 2, .str = "RES 7, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xBA }, .opcode_len = 2, .str = "RES 7, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xBB }, .opcode_len = 2, .str = "RES 7, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xBC }, .opcode_len = 2, .str = "RES 7, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xBD }, .opcode_len = 2, .str = "RES 7, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xBE }, .opcode_len = 2, .str = "RES 7, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xBF }, .opcode_len = 2, .str = "RES 7, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xC0 }, .opcode_len = 2, .str = "SET 0, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xC1 }, .opcode_len = 2, .str = "SET 0, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xC2 }, .opcode_len = 2, .str = "SET 0, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xC3 }, .opcode_len = 2, .str = "SET 0, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xC4 }, .opcode_len = 2, .str = "SET 0, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xC5 }, .opcode_len = 2, .str = "SET 0, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xC6 }, .opcode_len = 2, .str = "SET 0, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xC7 }, .opcode_len = 2, .str = "SET 0, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xC8 }, .opcode_len = 2, .str = "SET 1, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xC9 }, .opcode_len = 2, .str = "SET 1, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xCA }, .opcode_len = 2, .str = "SET 1, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xCB }, .opcode_len = 2, .str = "SET 1, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xCC }, .opcode_len = 2, .str = "SET 1, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xCD }, .opcode_len = 2, .str = "SET 1, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xCE }, .opcode_len = 2, .str = "SET 1, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xCF }, .opcode_len = 2, .str = "SET 1, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xD0 }, .opcode_len = 2, .str = "SET 2, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xD1 }, .opcode_len = 2, .str = "SET 2, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xD2 }, .opcode_len = 2, .str = "SET 2, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xD3 }, .opcode_len = 2, .str = "SET 2, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xD4 }, .opcode_len = 2, .str = "SET 2, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xD5 }, .opcode_len = 2, .str = "SET 2, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xD6 }, .opcode_len = 2, .str = "SET 2, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xD7 }, .opcode_len = 2, .str = "SET 2, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xD8 }, .opcode_len = 2, .str = "SET 3, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xD9 }, .opcode_len = 2, .str = "SET 3, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xDA }, .opcode_len = 2, .str = "SET 3, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xDB }, .opcode_len = 2, .str = "SET 3, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xDC }, .opcode_len = 2, .str = "SET 3, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xDD }, .opcode_len = 2, .str = "SET 3, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xDE }, .opcode_len = 2, .str = "SET 3, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xDF }, .opcode_len = 2, .str = "SET 3, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xE0 }, .opcode_len = 2, .str = "SET 4, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xE1 }, .opcode_len = 2, .str = "SET 4, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xE2 }, .opcode_len = 2, .str = "SET 4, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xE3 }, .opcode_len = 2, .str = "SET 4, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xE4 }, .opcode_len = 2, .str = "SET 4, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xE5 }, .opcode_len = 2, .str = "SET 4, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xE6 }, .opcode_len = 2, .str = "SET 4, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xE7 }, .opcode_len = 2, .str = "SET 4, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xE8 }, .opcode_len = 2, .str = "SET 5, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xE9 }, .opcode_len = 2, .str = "SET 5, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xEA }, .opcode_len = 2, .str = "SET 5, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xEB }, .opcode_len = 2, .str = "SET 5, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xEC }, .opcode_len = 2, .str = "SET 5, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xED }, .opcode_len = 2, .str = "SET 5, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xEE }, .opcode_len = 2, .str = "SET 5, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xEF }, .opcode_len = 2, .str = "SET 5, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xF0 }, .opcode_len = 2, .str = "SET 6, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xF1 }, .opcode_len = 2, .str = "SET 6, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xF2 }, .opcode_len = 2, .str = "SET 6, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xF3 }, .opcode_len = 2, .str = "SET 6, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xF4 }, .opcode_len = 2, .str = "SET 6, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xF5 }, .opcode_len = 2, .str = "SET 6, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xF6 }, .opcode_len = 2, .str = "SET 6, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xF7 }, .opcode_len = 2, .str = "SET 6, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xF8 }, .opcode_len = 2, .str = "SET 7, B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xF9 }, .opcode_len = 2, .str = "SET 7, C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xFA }, .opcode_len = 2, .str = "SET 7, D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xFB }, .opcode_len = 2, .str = "SET 7, E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xFC }, .opcode_len = 2, .str = "SET 7, H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xFD }, .opcode_len = 2, .str = "SET 7, L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xFE }, .opcode_len = 2, .str = "SET 7, (HL)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xCB, 0xFF }, .opcode_len = 2, .str = "SET 7, A", .numbytes = 1, .argtype = 0, },

	{ .opcode = { 0xED, 0x40 }, .opcode_len = 2, .str = "IN B, (C)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x41 }, .opcode_len = 2, .str = "OUT (C), B", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x42 }, .opcode_len = 2, .str = "SBC HL, BC", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x43 }, .opcode_len = 2, .str = "LD (^), BC", .numbytes = 3, .argtype = 0, },
	{ .opcode = { 0xED, 0x44 }, .opcode_len = 2, .str = "NEG", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x45 }, .opcode_len = 2, .str = "RETN", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x46 }, .opcode_len = 2, .str = "IM 0", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x47 }, .opcode_len = 2, .str = "LD I, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x48 }, .opcode_len = 2, .str = "IN C, (C)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x49 }, .opcode_len = 2, .str = "OUT (C), C", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x4A }, .opcode_len = 2, .str = "ADC HL, BC", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x4B }, .opcode_len = 2, .str = "LD BC, (^)", .numbytes = 3, .argtype = 0, },
	{ .opcode = { 0xED, 0x4C }, .opcode_len = 2, .str = "NEG", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x4D }, .opcode_len = 2, .str = "RETN", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x4E }, .opcode_len = 2, .str = "IM 0", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x4F }, .opcode_len = 2, .str = "LD R, A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x50 }, .opcode_len = 2, .str = "IN D, (C)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x51 }, .opcode_len = 2, .str = "OUT (C), D", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x52 }, .opcode_len = 2, .str = "SBC HL, DE", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x53 }, .opcode_len = 2, .str = "LD (^), DE", .numbytes = 3, .argtype = 0, },
	{ .opcode = { 0xED, 0x54 }, .opcode_len = 2, .str = "NEG", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x55 }, .opcode_len = 2, .str = "RETN", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x56 }, .opcode_len = 2, .str = "IM 1", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x57 }, .opcode_len = 2, .str = "LD A, I", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x58 }, .opcode_len = 2, .str = "IN E, (C)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x59 }, .opcode_len = 2, .str = "OUT (C), E", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x5A }, .opcode_len = 2, .str = "ADC HL, DE", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x5B }, .opcode_len = 2, .str = "LD DE, (^)", .numbytes = 3, .argtype = 0, },
	{ .opcode = { 0xED, 0x5C }, .opcode_len = 2, .str = "NEG", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x5D }, .opcode_len = 2, .str = "RETN", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x5E }, .opcode_len = 2, .str = "IM 2", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x5F }, .opcode_len = 2, .str = "LD A, R", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x60 }, .opcode_len = 2, .str = "IN H, (C)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x61 }, .opcode_len = 2, .str = "OUT (C), H", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x62 }, .opcode_len = 2, .str = "SBC HL, HL", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x63 }, .opcode_len = 2, .str = "LD (^), HL", .numbytes = 3, .argtype = 0, },
	{ .opcode = { 0xED, 0x64 }, .opcode_len = 2, .str = "NEG", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x65 }, .opcode_len = 2, .str = "RETN", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x66 }, .opcode_len = 2, .str = "IM 0", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x67 }, .opcode_len = 2, .str = "RRD", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x68 }, .opcode_len = 2, .str = "IN L, (C)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x69 }, .opcode_len = 2, .str = "OUT (C), L", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x6A }, .opcode_len = 2, .str = "ADC HL, HL", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x6B }, .opcode_len = 2, .str = "LD HL, (^)", .numbytes = 3, .argtype = 0, },
	{ .opcode = { 0xED, 0x6C }, .opcode_len = 2, .str = "NEG", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x6D }, .opcode_len = 2, .str = "RETN", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x6E }, .opcode_len = 2, .str = "IM 0", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x6F }, .opcode_len = 2, .str = "RLD", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x70 }, .opcode_len = 2, .str = "IN F, (C)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x71 }, .opcode_len = 2, .str = "OUT (C), 0", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x72 }, .opcode_len = 2, .str = "SBC HL, SP", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x73 }, .opcode_len = 2, .str = "LD (^), SP", .numbytes = 3, .argtype = 0, },
	{ .opcode = { 0xED, 0x74 }, .opcode_len = 2, .str = "NEG", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x75 }, .opcode_len = 2, .str = "RETN", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x76 }, .opcode_len = 2, .str = "IM 1", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x78 }, .opcode_len = 2, .str = "IN A, (C)", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x79 }, .opcode_len = 2, .str = "OUT (C), A", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x7A }, .opcode_len = 2, .str = "ADC HL, SP", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x7B }, .opcode_len = 2, .str = "LD SP, (^)", .numbytes = 3, .argtype = 0, },
	{ .opcode = { 0xED, 0x7C }, .opcode_len = 2, .str = "NEG", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x7D }, .opcode_len = 2, .str = "RETN", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0x7E }, .opcode_len = 2, .str = "IM 2", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0xA0 }, .opcode_len = 2, .str = "LDI", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0xA1 }, .opcode_len = 2, .str = "CPI", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0xA2 }, .opcode_len = 2, .str = "INI", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0xA3 }, .opcode_len = 2, .str = "OUTI", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0xA8 }, .opcode_len = 2, .str = "LDD", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0xA9 }, .opcode_len = 2, .str = "CPD", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0xAA }, .opcode_len = 2, .str = "IND", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0xAB }, .opcode_len = 2, .str = "OUTD", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0xB0 }, .opcode_len = 2, .str = "LDIR", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0xB1 }, .opcode_len = 2, .str = "CPIR", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0xB2 }, .opcode_len = 2, .str = "INIR", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0xB3 }, .opcode_len = 2, .str = "OTIR", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0xB8 }, .opcode_len = 2, .str = "LDDR", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0xB9 }, .opcode_len = 2, .str = "CPDR", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0xBA }, .opcode_len = 2, .str = "INDR", .numbytes = 1, .argtype = 0, },
	{ .opcode = { 0xED, 0xBB }, .opcode_len = 2, .str = "OTDR", .numbytes = 1, .argtype = 0, },
};

